### ISSUE TITLE
Bootkit != Bootlocker

### ISSUE THREAD

**Issue by yarfuo** [Whiroo/SimpleBootlocker#1]
Буткит; Используется вредоносными программами для получения максимальных привилегий в операционных системах. Буткит может получить права администратора (суперпользователя) и выполнять любые вредоносные действия.

https://ru.wikipedia.org/wiki/%D0%91%D1%83%D1%82%D0%BA%D0%B8%D1%82

Если верить описанию с xor'ом MBR, то тогда нужно исправить описание на "бутлокер" ^.^

**Comment by Whiroo** [comment]
Да, пожалуй ты прав, спасибо!
